CREATE SEQUENCE IF NOT EXISTS PK_ENQUIRY
AS BIGINT
INCREMENT BY 1
MINVALUE 0
START 0;

CREATE TABLE IF NOT EXISTS ENQUIRY(
    id BIGINT PRIMARY KEY not null,
    EMAIL VARCHAR(20) NOT NULL,
    FIRSTNAME VARCHAR(15) NOT NULL,
    LASTNAME VARCHAR(15) NOT NULL,
    LEARNING_MODE VARCHAR(10) NOT NULL,
    MESSAGE VARCHAR(100),
    CREATED_ON timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ENQUIRY_LAST_DOWNLOADED(
    ID BIGINT PRIMARY KEY,
    ENQUIRY_LAST_DOWNLOADED TIMESTAMP
);

INSERT INTO ENQUIRY_LAST_DOWNLOADED (ID, ENQUIRY_LAST_DOWNLOADED) VALUES (1, NOW());

