CREATE TABLE IF NOT EXISTS COURSE(
    COURSE VARCHAR(35) PRIMARY KEY,
    DESCRIPTION VARCHAR(50) NOT NULL,
    ORIGINAL_PRICE DECIMAL DEFAULT 0,
    FINAL_PRICE DECIMAL DEFAULT 0,
    DISCOUNT DECIMAL DEFAULT 0,
    COURSE_CATEGORY VARCHAR(8) NOT NULL,
    CONSTRAINT FK_COURSE_CATEGORY FOREIGN KEY(COURSE_CATEGORY) REFERENCES COURSE_CATEGORY(CATEGORY)
);