CREATE TABLE IF NOT EXISTS COMBOS_HD(
    COMBO_CODE VARCHAR(20) PRIMARY KEY,
    COMBO_DESC VARCHAR(50) NOT NULL,
    NEXT_BATCH_DATE DATE NOT NULL,
    PRICE DECIMAL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS COMBOS_DT (

    COMBO_CODE VARCHAR(20),
    COURSE VARCHAR(10),
    PRIMARY KEY (COMBO_CODE, COURSE),
    CONSTRAINT FK_COURSE FOREIGN KEY(COURSE) references COURSE(COURSE)

);